# -*- coding: utf-8 -*-
"""
/***************************************************************************
 hedgerow_planner
                                 A QGIS plugin
 This script will make a raster of plant positions from a line object
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-27
        copyright            : (C) 2024 by Nationalparkverein Unteres Odertal,  Lars Schulz
        email                : l.schulz@nationalpark-unteres-odertal.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load hedgerow_planner class from file hedgerow_planner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hedgerow_planner import hedgerow_planner
    return hedgerow_planner(iface)
