# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HedgerowPlanner
                                 A QGIS plugin
 This script initializes the plugin, making it known to QGIS.
 Generated by Plugin Builder
                             -------------------
        begin                : 2024-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Nationalparkverein Unteres Odertal,  Lars Schulz
        email                : l.schulz@nationalpark-unteres-odertal.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

def classFactory(iface):
    from .hedgerow_planner import HedgerowPlanner
    return HedgerowPlanner(iface)
