# -*- coding: utf-8 -*-
"""
/***************************************************************************
 hedgerow_plannerDialog
                                 A QGIS plugin
 This script will make a raster of plant positions from a line object
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-27
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Nationalparkverein Unteres Odertal,  Lars Schulz
        email                : l.schulz@nationalpark-unteres-odertal.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from PyQt5 import uic
from PyQt5.QtWidgets import QDialog
import os

# Load the UI file
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'hedgerow_planner_dialog_base.ui'))

class HedgerowPlannerDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(HedgerowPlannerDialog, self).__init__(parent)
        self.setupUi(self)
