# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hedgerow_planner_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
        self.buttonBox.setStandardButtons(QtCore.Qt.QDialogButtonBox::StandardButton::Cancel|QtCore.Qt.QDialogButtonBox::StandardButton::Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.rows_spinbox = QtWidgets.QSpinBox(Dialog)
        self.rows_spinbox.setGeometry(QtCore.QRect(150, 60, 42, 22))
        self.rows_spinbox.setObjectName("rows_spinbox")
        self.row_spacing_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.row_spacing_spinbox.setGeometry(QtCore.QRect(130, 100, 62, 22))
        self.row_spacing_spinbox.setObjectName("row_spacing_spinbox")
        self.plant_spacing_spinbox = QtWidgets.QDoubleSpinBox(Dialog)
        self.plant_spacing_spinbox.setGeometry(QtCore.QRect(130, 140, 62, 22))
        self.plant_spacing_spinbox.setObjectName("plant_spacing_spinbox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 60, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 81, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Rows"))
        self.label_2.setText(_translate("Dialog", "Row spacing"))
        self.label_3.setText(_translate("Dialog", "Plant spacing"))
